remote_theme: pages-themes/cayman@v0.2.0
# theme: minima

# Google Analytics
google_analytics: G-E5KEG7QSYW
 
collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "digests"
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme # add this line to the plugins list if you already have one
